config/routes.rb
Stc::Application.routes.draw do


  post 'portfolios/create' => 'portfolios#create'

  resources :stocks do
    collection do
      get 'manage_list'
      get 'lookup'
      get 'new_portfolio'
      post 'sell_shares'
      get 'family_fun_positions'
      get 'new_price_time'
    end
  end

  resources :attachments 

  resources :comments do
    member do
      get 'modify'
    end
  end

  resources :posts do
    collection do
      get 'add_comment'
      get 'add_attachment'
    end
  end
    
#  authenticated :user do
#    root :to => 'home#index'
#    root :to => 'home#welcome'
#  end

  root :to => 'home#start'
  
  devise_for :users
  resources :users
  
  get 'home/welcome' => 'home#welcome', :as => :welcome
  get 'home/index' => 'home#index', :as => :index
  get 'home/news' => 'home#news', :as => :news
  get 'home/pictures' => 'home#pictures', :as => :pictures
  get 'home/media' => 'home#media', :as => :media
  
  get 'home/start' => 'home#start', :as => :start
  get 'home/test_graph' => 'home#test_graph', :as => :test_graph
  
  
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user
  belongs_to :portfolio
  attr_accessible :name, :last_price, :last_price_date, :price_change, :quantity, :portfolio_id, :purch_date, :purch_price, :symbol, :user_id, :comments_attributes
  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :comments, :allow_destroy => true
  
  validates_numericality_of :purch_price
  validates :purch_date, :presence => true
  validates_numericality_of :quantity, :presence => true

    def current_price  
      Quote.current_price(self.symbol)['LastTrade'].to_f
    end  
    
    def todays_change
      quote = Quote.current_price(self.symbol)
      price_change = quote['Change'].to_f
      percent_change = price_change / quote['LastTrade'].to_f
      return price_change, percent_change
    end

    def position_cost
      self.quantity * self.purch_price
    end
    
    def position_value
      self.quantity * self.current_price
    end
    
    def position_gain_loss
      g_l = 0
      g_l_p = 0
      if self.quantity > 0
        g_l = self.position_value - self.position_cost
        g_l_p = g_l / self.position_cost
      end
      return g_l, g_l_p
    end
        
    def self.add_position(params)
      stock = Stock.new(params)
      portfolio = Portfolio.find(stock.portfolio)
      portfolio.cash -= (stock.purch_price * stock.quantity)
      if stock.save and portfolio.save 
        return stock
      else
        return false
      end    
    end
    
    def sell_position(shares)      
      self.quantity = self.quantity.to_i - shares.to_i
      p = Portfolio.find(self.portfolio_id)
      p.cash += shares.to_i * self.current_price
      self.save
      p.save
    end

    
#    def self.portfolio(port_name,sort_order,current_user)
#      Portfolio.where(:name => port_name, :user_id => current_user).first.rank_by_gain_loss(sort_order)     
#     portfolio = [ ]
#     stocks.each do |p|        
#       lookup = Quote.current_price(p.symbol)
#     # symbol-0, user.name-1, purch_price-2, purch_date-3, gain_loss-4, company-5, symbol-6, current_price-7, change-8, gain_loss-9
#     portfolio.push [ p.symbol,
#                      p.user.name,
#                      p.purch_price,
#                      p.purch_date,
#                      p.position_gain_loss, # (lookup['LastTrade'].to_f - p.purch_price) / p.purch_price, 
#                      lookup['Name'],
#                      p.symbol.upcase,
#                      p.current_price, # 7
#                      p.todays_change,
#                      p.position_gain_loss,
#                      p.position_gain_loss_percent,
#                      p.quantity, # 11
#                      p.id ]
#                      
#     end
#      if sort_order == 'overall'
#        portfolio.sort_by!{|k| -k[4]}
#      else
#        portfolio.sort_by!{|k| -k[4]}
#      end
#      return stocks
#    end
  
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_filter :authenticate_user!
  # GET /stocks
  # GET /stocks.json
  
  def new_price_time
    indexes = Quote.get_indexes
    message = '| S&P 500: ' + indexes[1]['LastTrade'] +
    ' ' + indexes[1]['Change'] + ' , Nasdaq: ' +
    indexes[0]['LastTrade'] + ' ' + indexes[0]['Change'] +
#    ' | Refresh in: ' + (3600 - ('%.0f' % (Time.now - Stock.last.updated_at).to_s).to_i).to_s  + ' secs'
    ' | Prices are ' + '%.0f' % (Time.now - Stock.last.updated_at).to_s  + ' secs old'
    npt = Hash.new
    npt['time_next'] = message
    render :json => npt
    
  end
  
  def family_fun_positions
    @port = params[:portfolio]
    @port ||= 'Family Fun'
    @portfolios = Portfolio.where(:name => @port) # Portfolio.where(:name => 'Family Fun')
  	series = Translog.db_daily_snapshot(@portfolios)
  	@line = series[0].inspect
  	@colors = series[1]
  	@names = series[2]
    respond_to do |format|
      format.html # show.html.erb
      format.js # { render json: @stock }
    end
    
  end
  
  def sell_shares
    stock = Stock.find(params[:stock_id])
    stock.sell_position(params[:shares])  
    PostLogger.info("Sell position - Now: #{stock.quantity} shares of #{stock.symbol} in #{stock.portfolio.user.name}'s - #{stock.portfolio.name} Portfolio")
          
    redirect_to stocks_path( :portfolio => params[:portfolio])    
  end
  
  def new_portfolio
    @portfolio = Portfolio.new :cash => 10000.00    
  end
  
  def lookup
    price = Quote.get_quotes([ params[:symbol] ]).first
    render :text => price['LastTrade'].to_s  + '#&#' + price['Name'] + '#&#' + price['Change'].to_f.to_s  
  end

  def manage_list
#    @stocks = Stock.portfolio(params[:portfolio_view],params[:type_of_action]) # where(:portfolio => params[:portfolio])
    @stocks = Portfolio.where(:name => params[:portfolio_view], :user_id => current_user).first.rank_by_gain_loss(params[:type_of_action])    
    @port = params[:portfolio_view]
  end
  
  def index
    @error = params[:error]    
    @view = params[:view] ||= 'Performance'
    @port = params[:portfolio] ||= Portfolio.where(:user_id => current_user).first.name if !Portfolio.where(:user_id => current_user).empty?
    @stocks = Portfolio.where(:name => @port, :user_id => current_user).first.rank_by_gain_loss(params[:type_of_action]) 
    @portfolio = Portfolio.new :cash => 100000.0
     if params[:type_of_action]
       if params[:type_of_action] == 'overall'
         render :partial => 'overall_action.mobile', :layout => false
       else
         render :partial => 'todays_action.mobile', :layout => false
       end
     end
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @stock = Stock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stock }
    end
  end

  # GET /stocks/new
  # GET /stocks/new.json
  def new
    @port = params[:portfolio_view]
    @stock = Stock.new
    @stock.comments.build
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stock }
    end
  end

  # GET /stocks/1/edit
  def edit
    @stock = Stock.find(params[:id])
    @port = params[:portfolio]
    
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.add_position(params[:stock])
    if @stock
      PostLogger.info("Add position - Now: #{@stock.quantity} shares of #{@stock.symbol} in #{@stock.portfolio.user.name}'s - #{@stock.portfolio.name} Portfolio")
      redirect_to stocks_path( :portfolio => @stock.portfolio.name )
    else
      @stock = Stock.new # added with controller tests and commented out the next line
#      @error = @stock.errors.full_messages
      render action: "new"
    end
    
#    respond_to do |format|
#      if @stock.save
#        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
#        format.json { render json: @stock, status: :created, location: @stock }
#      else
#        format.html { render action: "new" }
#        format.json { render json: @stock.errors, status: :unprocessable_entity }
#      end
#    end

  end

  # PUT /stocks/1
  # PUT /stocks/1.json
  def update
    @stock = Stock.find(params[:id])

    respond_to do |format|
      if @stock.update_attributes(params[:stock])
        PostLogger.info("Change position - Now: #{@stock.quantity} shares of #{@stock.symbol} in #{@stock.portfolio.user.name}'s - #{@stock.portfolio.name} Portfolio")

        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_index.html.erb
<%= render 'tabs' %>				

<table class='table table-condensed table-bordered table-striped'>
			
		<tr>
			<th colspan=6 class='aln_c'>Position</th>
			<th colspan=2 class='aln_c'>Daily Result</th>
			<th colspan=2 class='for_day aln_c'>Gain/Loss</th>
		</tr>
		<tr>
			<th>Stock</th>
			<th>Quantity Held</th>
			<th>Sell</th>
			<th class='aln_c'>Purchase Price</th>
			<th class='aln_c'>Days Held</th>
			<th class='aln_c'>Current Value</th>
			<th class='aln_c'>Current Price</th>
			<th class='aln_c'>Change</th>
			<th class='aln_c'>Daily</th>
			<th class='aln_c'>Overall</th>
		</tr>

<% @stocks.each_with_index do |stock| %>

	<tr>
		<td><%= stock.name %>[<%= stock.symbol.upcase %>]</td>
		<td class='aln_r'><p><%= number_with_precision(stock.quantity, :delimiter => ',', :precision => 0) %></td>
		<td><div class="dropdown">
			  <a class="dropdown-toggle btn btn-mini btn-warning" data-toggle="dropdown" href="#">Sell</a>
			  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
				  <div class="modal-body">
					<%= form_tag(sell_shares_stocks_path(:portfolio => @port), :class => 'form-horizontal' ) do %>
					  	<p><%= stock.quantity %> shares of <%= stock.symbol.upcase %></p>
					    sell <%= text_field_tag :shares ,'', :class => 'span1' %><br>
						<%= hidden_field_tag :stock_id, stock.id %>
						<%= hidden_field_tag :price, stock.current_price %>
						
				  </div>
				  <div class="modal-footer">
					    <%= submit_tag 'Sell Shares', :class => 'btn btn-warning btn-mini'%>	
				    <button class="btn btn-mini" data-dismiss="modal" aria-hidden="true">Close</button>
					<% end %>	
				  </div>
			  </ul>
			</div>
			</p>
		</td>
		<td class='aln_r'><%= number_to_currency(stock.purch_price) %></td>
		<td class='aln_r'><%= distance_of_time_in_words(stock.purch_date, Date.today) %> </td> <!-- Holding Period -->
		<td class='aln_r'><%= number_to_currency(stock.position_value) %></td>
		<td class='aln_r'><%= number_to_currency(stock.current_price) %></td>
		<td class='aln_r'><%= number_to_currency(stock.todays_change[0]) %> (<%= number_to_percentage 100*stock.todays_change[1] %> )</td>
		<td class='aln_r'><%= number_to_currency(stock.quantity * stock.todays_change[0]) %></td> <!-- Gain/Loss -->
		<td class='aln_r'><%= number_to_currency(stock.position_gain_loss[0]) %></td>
  </tr>
	<% end %>

	<tr><td colspan=10></td></tr>	
<tr>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<th class='aln_r'>Cash</th>
	<td class='aln_r'><%= number_to_currency(Portfolio.where(:name => @port, :user_id => current_user).first.cash) %></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
<tr>
	<tr><td colspan=10></td></tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<th class='aln_r'>Total</th>
		<td class='aln_r'><%= number_to_currency(Portfolio.where(:name => @port, :user_id => current_user).first.current_value) %></td>
		<th  colspan=2 class='aln_r'>Unrealized Gain/Loss</th>
		<td class='aln_r'><%= number_to_currency(Portfolio.where(:name => @port, :user_id => current_user).first.unrealized_gain_loss[1] ) %></td>
		<td class='aln_r'><%= number_to_currency(Portfolio.where(:name => @port, :user_id => current_user).first.unrealized_gain_loss[0] ) %></td>
	<tr>
		

</table>

app/views/stocks/_overall_action.mobile.erb
<table class="ui-body-d ui-shadow table-stripe ui-responsive" data-rel="dialog"  style="margin: auto;">
	<thead><tr><td colspan=4 style='text-align:center;'>
		<div id='pv' style='display:none;'><%= @port %></div>
			<% Time.zone = 'America/New_York' %>
		Overall Performance as of: <%= Time.now.strftime(" %I:%M%p") %> EST<br>
	</td></tr> 
	</thead>         
 
           <tr class="ui-bar-d">
             <th>Stock</th>
             <th>Current<br>Value</th>
             <th>Days<br>Held</abbr></th>
             <th>Gain/<br>Loss</th>
           </tr>
         <tbody>

				<% @stocks.each_with_index do |stock,i| %>
					<%= i.odd? ? "<tr style='background: #eee;' >".html_safe : "<tr>".html_safe %>
						<td style='border-bottom: 1px solid #000;'><%= stock.symbol.upcase %></td>
						<td style='text-align:right !important;border-bottom: 1px solid #000;'><%= number_to_currency stock.position_value %></td>
						<td style='text-align:right !important;border-bottom: 1px solid #000;'><%= Quote.distance_of_time_in_days(stock.purch_date, Date.today) %></td> <!-- Gain/Loss -->
						<td style='text-align:right !important;border-bottom: 1px solid #000;'><%= number_to_currency stock.position_gain_loss[0], :precision => 2 %></td>
				  </tr>
				<% end %>
			<tr style='border-bottom: 1px solid #000;'>
				<td style='border-bottom: 1px solid #000;'>Cash</td>
				<td style='text-align:right !important;border-bottom: 1px solid #000;'><%= number_to_currency(Portfolio.where(:name => @port, :user_id => current_user).first.cash) %></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>Total</td>
				<td style='text-align:right !important;'><%= number_to_currency(Portfolio.where(:name => @port, :user_id => current_user).first.current_value) %></td>
			</tr>

         </tbody>
       </table>

app/views/stocks/family_fun_positions.html.erb
<script class="include" language="javascript" type="text/javascript" src="/assets/jqplot/jqplot.dateAxisRenderer.min.js"></script>


<script>

$(document).ready(function(){
	PortfolioGraph()
	
	$('#portfolio_id').change(function () {
	PortfolioGraph() ;
	});	
});

function PortfolioGraph() {
  	StartSpinner() ;
   	Portfolio_is = document.getElementById('portfolio_id').value ;
        $.get('/stocks/family_fun_positions', { portfolio:Portfolio_is} , null, 'script');
        return false;
		};


</script>

<%= link_to 'Home', start_path, :class => 'btn btn-mini'%><br><br>

<b style='font-size:16pt;'>Select Portfolio:</b> <%= select_tag("portfolio_id", options_for_select(Portfolio.where(:user_id => current_user).collect {|p| [ p.name] }, @port ) ) %>
<div id='spinner' style='display:none;'><%= image_tag '/assets/ajax-loader.gif' %></div>			

<table style="margin: auto;">
  <tr>
	<td><td>
	<td>
		<div style="text-align:center;" id='index'>
	</td>
	<td></td>
  </tr>
</table>
<br><br>

app/views/stocks/family_fun_positions.mobile.erb
<div data-theme="b" data-role="header">
	<span class="ui-title">
    </span>
	<%= link_to_function "Home", "GoHome();", 'data-transition' => "fade", 'data-theme' => "a", 'data-icon' => "home" %>

    <%= link_to 'Logout', destroy_user_session_path(:user), :method=>'delete', 'data-role' => "button", 'data-inline' => "true", 'data-direction' => "reverse", 'data-theme' => "a", 'data-icon' => "star", 'data-iconpos' => "left", :class => "ui-btn-right" %>
    </a>
</div>

   <div data-role="content">	
<br>	

		<% Time.zone = 'America/New_York' %>
      <p>Latest Results as of: <%= Time.now.strftime("%I:%M%p") %> EST</p>
 
<table data-role="table" id="table-custom-2" data-mode="columntoggle" class="ui-body-d ui-shadow table-stripe ui-responsive" data-column-btn-theme="b" data-column-btn-text="Columns to display..." data-column-popup-theme="a" style="margin: auto;">

		<tr class="ui-bar-d">
			<th>Stock</th>
			<th>Owner</th>
			<th class='aln_c'>Days Held</th>
			<th class='aln_c'>Gain/Loss</th>
		</tr>

	<% s = Portfolio.where(:name => 'Family Fun').collect { |p| p }.collect { |p| p.stocks }.flatten %>
	<% stocks = s.collect { |stock| [ stock, stock.position_gain_loss[1] ] }.sort_by! { |i| -i[1] } %>

	<% stocks.each_with_index do |s,i| %>
	<% stock = s[0]%>
		<% if stock.quantity > 0 %>
		<%= i.odd? ? "<tr style='background: #eee;' >".html_safe : "<tr>".html_safe %>
			<td><%= stock.symbol.upcase %></td>
			<td><%= stock.portfolio.user.name %></td>
			<td style='text-align:right !important;'><%= distance_of_time_in_words(stock.purch_date, Date.today) %> </td> <!-- Holding Period -->
			<td style='text-align:right !important;'><%= number_to_percentage(100*(stock.current_price-stock.purch_price)/stock.purch_price) %></td>
  		</tr>
		<% end %>
	<% end %>

</table>
<br>

<br>
<br>
</div><!-- /content -->

<div data-role="footer">
      <h1>Denenberg @2012 | <%= link_to "Full Site", start_path(:mobile => 0), :target => '_blank' %></h1>
</div><!-- /header -->

app/views/stocks/index.html.erb
<script>
	$('#myModal').modal('show') ;
	
</script>

<script>
function callModal(stock) {
	$("#shares").text (stock);
	$('#sellStockModal').modal('show') ;
}
</script>

<style>
#myModal {
    width: 300px; /* SET THE WIDTH OF THE MODAL */
    margin: -250px 0 0 -150px; /* CHANGE MARGINS TO ACCOMODATE THE NEW WIDTH (original = margin: -250px 0 0 -280px;) */
}

</style>

<%= link_to 'Home', start_path, :class => 'btn btn-mini'%><br><br>

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= msg %>
</div>
  <% end %>
<% end %>

<%= render '/stocks/partials/new_portfolio' %>

	<div class="row">		
        <div class="span12 schoolbox">
	
			<div class='well' style='background-color:white;'>	
					
				<%= select_tag "portfolio_is", options_for_select(Portfolio.where(:user_id => current_user.id).collect { |p| p.name }, :selected => @port), :class => 'span2' %>
				<!--  -->

				<%= link_to 'New Portfolio', '#myModal', :class => 'btn btn-mini btn-info', 'data-toggle' => "modal" %>
				<%= link_to 'Add Position', new_stock_path(:portfolio_view => @port), :class => 'btn btn-mini btn-primary' %>	
				<%= link_to 'Graph Performance', family_fun_positions_stocks_path(:portfolio => @port), :class => 'btn btn-mini btn-success' %>	
				<div id='spinner' style='display:none;'><%= image_tag '/assets/ajax-loader.gif' %></div>			
				
				<div id='portfolio_list'>
				<%= render 'index' %>
				</div>
				

	</div><!--/well-->	
   </div><!--/span-->
</div><!--/row-->

<br />

app/views/stocks/index.mobile.erb
<script>

/Mobile/.test(navigator.userAgent) && !location.hash && setTimeout(function () {
    if (!pageYOffset) window.scrollTo(0, 1);
}, 1000);

function ManageList()
  {
	PV = $("#pv").text();
	window.location = '/stocks/manage_list?mobile=1&portfolio_view=' + PV ;
  }


$(document).ready(function(){
SelectList('overall') ;
})

function SelectList(Action) {
    var selected = $("#portfolio-select option:selected").text();
	$.get('/stocks', 
      { portfolio:selected, type_of_action:Action },         
      function(data) { $("#port_list").html(data); }
	);
  }


$("#portfolio-select").change(function() {
SelectList('overall') ;
});

function NewPortfolioTest() {
	$("#new_portfolio").submit();
//	window.location = '/stocks?mobile=1' ;	
}

function AddPosition() {
    PV = $("#portfolio-select option:selected").text();
	window.location = '/stocks/new?mobile=1&portfolio_view=' + PV ;	
}

</script>


<div data-theme="b" data-role="header">
	<span class="ui-title">
    </span>
    
    <%= link_to_function 'Home', "GoHome();", 'data-role' => "button", 'data-inline' => "true", 'data-direction' => "reverse", 'data-theme' => "a", 'data-icon' => "home", 'data-iconpos' => "left", :class => "ui-btn-left" %>
   
    <%= link_to 'Logout', destroy_user_session_path(:user), :method=>'delete', 'data-role' => "button", 'data-inline' => "true", 'data-direction' => "reverse", 'data-theme' => "a", 'data-icon' => "star", 'data-iconpos' => "left", :class => "ui-btn-right" %>
    </a>
</div>


<div data-role="content">
		
		<div data-role="popup" id="new_portfolio_popup" data-theme="a" class="ui-corner-all">
			<%= simple_form_for(@portfolio, :url => portfolios_create_path(@portfolio)) do |f| %>
				<div style="padding:10px 20px;">
				  <h3>Create Portfolio</h3>
		          <label for="un" >Portfolio Name:</label>
			    	<%= f.text_field :name  %>

		          <label for="pw" >Initial Cash:</label>
				<%= f.text_field :cash, :value => number_with_precision(f.object.cash, :precision => 0) %>
				<%= f.hidden_field :user_id, :value => current_user.id %>


	<%= link_to_function 'Submit', 'NewPortfolioTest();', 'data-role' => "button", 'data-inline' => "true", 'data-theme' => "b" %>
	<a href="#" data-role="button" data-inline="true" data-rel="back" data-theme="c">Cancel</a>	    	  
				</div>
			<% end %>
		</div>
	
	<div class="ui-grid-a">
		 <div class="ui-block-a">
<a href="#new_portfolio_popup" data-rel="popup" data-position-to="window" data-role="button" data-inline="true" data-mini = "true">New Portfolio</a>
		</div>
		<div class="ui-block-b">	
<%= link_to_function 'Add position', 'AddPosition();', 'data-role' => "button", 'data-inline' => "true", 'data-theme' => "b", 'data-mini' => "false", 'data-mini' => "true" if Portfolio.first %>	
		</div>
	</div>
		
			
<%= select_tag "portfolio-select", options_for_select(Portfolio.where(:user_id => current_user.id).collect { |p| p.name }, :selected => @port), 'data-theme' => "b" %>	
	

<div id='port_list'>
</div>

<br>
<div data-role="navbar" data-iconpos="top">
    <ul>
        <li>
			<%= link_to_function "Today's<br>Action".html_safe, "SelectList('today');", 'data-transition' => "fade", 'data-theme' => "a", 'data-icon' => "star" %>
        </li>
        <li>
			<%= link_to_function "Overall<br>Action".html_safe, "SelectList('overall');", 'data-transition' => "fade", 'data-theme' => "a", 'data-icon' => "star", :class => "ui-btn-active ui-state-persist" %>
        </li>
        <li>
			<%= link_to_function "Manage<br>List".html_safe, "ManageList();", 'data-transition' => "fade", 'data-theme' => "a", 'data-icon' => "grid" %>
        </li>
    </ul>
</div>


      
         </div><!-- /content -->

<div data-role="footer" data-theme="b">
      <h1>Denenberg @2012 | <%= link_to "Full Site", stocks_path(:mobile => 0), :target => '_blank' %></h1>
</div><!-- /header -->

app/views/stocks/manage_list.mobile.erb
<div data-theme="b" data-role="header">
	<span class="ui-title">
    </span>    
	<%= link_to_function "Home", "GoHome1('#{@port}');", 'data-transition' => "fade", 'data-theme' => "a", 'data-icon' => "home" %>
</div>



<div data-role="content">
	
<%= select_tag "portfolio-select", options_for_select( [ @port ] , :selected => 'Family Favorites'), 'data-theme' => "b" %>	


<p><b>Manage List</b> as of: <%= Time.now.strftime(" %I:%M%p") %></p>

<table class="ui-body-d ui-shadow table-stripe ui-responsive" data-rel="dialog">
 
         <thead>
           <tr class="ui-bar-d">
             <th>Stock</th>
			 <th>Action</th>
           </tr>
         </thead>
         <tbody>

		<% @stocks.each_with_index do |stock,i| %>
			<%= i.odd? ? "<tr style='background: #eee;' >".html_safe : "<tr>".html_safe %>
				<th><%= stock.symbol.upcase %></th>
				<td>						
					<div class="ui-grid-a">
					    <div class="ui-block-a">
						<%= link_to 'Edit', '#', 'data-role' => "button", 'data-icon' => "grid", 'data-iconpos' => "left", 'data-mini' => "true", 'data-inline' => 'true', 'data-theme' => "b" %>							
						</div>
						<div class="ui-block-b">
						<%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' }, 'data-role' => "button", 'data-icon' => "minus", 'data-iconpos' => "left", 'data-mini' => "true", 'data-inline' => 'true', 'data-theme' => "e"  %>										
						</div>
					</div>
				</td>							
		  </tr>
		<% end %>
         </tbody>
       </table>

<br>
	<%= link_to 'Add Position', new_stock_path(:mobile => 1, :portfolio_view => @port), 'data-icon' => 'plus', 'data-role' => "button", 'data-inline' => "true", 'data-theme' => "b", 'data-mini' => "true" %><br>

	<br>
	<div data-role="navbar" data-iconpos="top">
	    <ul>
	        <li>
				<%= link_to_function "Today's<br>Action".html_safe, "GoHome1('#{@port}');", 'data-transition' => "fade", 'data-theme' => "a", 'data-icon' => "star" %>
	        </li>
	        <li>
				<%= link_to_function "Overall<br>Action".html_safe, "GoHome1('#{@port}');", 'data-transition' => "fade", 'data-theme' => "a", 'data-icon' => "star" %>
	        </li>
	        <li>
				<%= link_to "Manage<br>List".html_safe, '#', 'data-transition' => "fade", 'data-theme' => "a", 'data-icon' => "plus", :class => "ui-btn-active ui-state-persist" %>
	        </li>
	    </ul>
	</div>



	         </div><!-- /content -->

	<div data-role="footer" data-theme="b">
	      <h1>Denenberg @2012 | <%= link_to "Full Site", stocks_path(:mobile => 0), :target => '_blank' %></h1>
	</div><!-- /header -->