config/routes.rb
Stc::Application.routes.draw do


  post 'portfolios/create' => 'portfolios#create'

  resources :stocks do
    collection do
      get 'manage_list'
      get 'lookup'
      get 'new_portfolio'
      post 'sell_shares'
      get 'family_fun_positions'
      get 'new_price_time'
    end
  end

  resources :attachments 

  resources :comments do
    member do
      get 'modify'
    end
  end

  resources :posts do
    collection do
      get 'add_comment'
      get 'add_attachment'
    end
  end
    
#  authenticated :user do
#    root :to => 'home#index'
#    root :to => 'home#welcome'
#  end

  root :to => 'home#start'
  
  devise_for :users
  resources :users
  
  get 'home/welcome' => 'home#welcome', :as => :welcome
  get 'home/index' => 'home#index', :as => :index
  get 'home/news' => 'home#news', :as => :news
  get 'home/pictures' => 'home#pictures', :as => :pictures
  get 'home/media' => 'home#media', :as => :media
  
  get 'home/start' => 'home#start', :as => :start
  get 'home/test_graph' => 'home#test_graph', :as => :test_graph
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :except => :welcome
  layout :choose_layout
  
  def test_graph
    render :layout => false 
  end
  
  def news
  end
  
  def pictures
  end
  
  def welcome
  end
  
  def start 
    @news = Post.where(:type_is => 'News').paginate(:page => params[:page], :per_page => 2)   
    @disc = Post.where(:type_is => 'Discussion').paginate(:page => params[:page], :per_page => 2).order('created_at desc')   
  end
  
  def index
    @users = User.all
  end

private
  def choose_layout    
    if [ 'events' ].include? action_name
      'blank'
    else
      'application'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class='row'>
	<div class='span8 offset1'>
		
	<div class='row'>
		<div class='pull-right'>
			<%= image_tag('BeforeIFound.png') %>
		</div>
	</div>



	<div class='row'>
		<div class='span7'>
			<%= image_tag('StandTallBanner.png', :size => '500x148') %>
		</div>
	</div>

<br>
	<div class='row'>
		<div class='span6 offset1 double_space'>
Most people rarely hear these types of stories about a school. But they represent a common sentiment among the parents of Orthogenic School and Hyde Park Day School students.<br><br>
At first glance, our two schools might seem worlds apart. The Sonia Shankman Orthogenic School (affectionately known as the O-School) is a primarily residential school for bright students who are coping with profound emotional challenges. Our staff members address everything from academic abilities to life skills, self-control methods to medication, individual issues to family concerns.<br><br>
Right next to the O-School, Hyde Park Day School staff members work with a very different group of bright students whose learning challenges cannot be met in mainstream schools. Teachers and other professionals foster academic mastery while boosting students’ confidence and helping them understand and address their learning strengths and challenges.<br><br>

Despite their differences, our two Schools share a single powerful mission:<br> 
<em style='color:#ff0000;font-size:16px;'>To transform the lives of students and families by helping them recognize and accommodate their learning and emotional challenges.</em><br><br>

Here, countless children who would otherwise have nowhere to turn are embraced, nurtured, and set 
on their feet again ... loving families that would otherwise be torn apart regain their balance ... and a community that would otherwise overlook the talents of our youth instead can be enriched by their 
incredible gifts.<br><br> 
Thanks to these astonishing schools, students stand tall, secure in their worth and abilities. Parents 
stand tall, proud of their wonderful children. We all stand tall, honored to recognize and accept the 
gifts of our entire community.<br><br>

</div>
</div>

</div>
</div>

<br>

<ul class="pager">
  <li>
    <a href="#">Previous</a>
  </li>
  <li>
    <a href="#">Next</a>
  </li>
</ul>

app/views/home/mobile.html.erb
<div data-role="header">

      <h1>DenVestR</h1>
      <a href="../../" data-icon="home" data-direction="reverse">Home</a>
      <a href="../nav.html" data-icon="search" data-rel="dialog" data-transition="fade">Search</a>
   </div><!-- /header -->

   <div data-role="content">
      <h2>Current Portfolio Results</h2>
      <p>THe Latest Results of our Picks</p>

    
       <table data-role="table" id="table-custom-2" data-mode="columntoggle" class="ui-body-d ui-shadow table-stripe ui-responsive" data-column-btn-theme="b" data-column-btn-text="Columns to display..." data-column-popup-theme="a">
        
                <thead>
                  <tr class="ui-bar-d">
                    <th data-priority="2">Mem</th>
                    <th>Symbol</th>
                    <th data-priority="3">Price</th>
                    <th data-priority="1"><abbr title="Rotten Tomato Rating">Change</abbr></th>
                    <th data-priority="5">Gain/Loss</th>
                  </tr>
                </thead>
                <tbody>

					<% @price.portfolio.each_with_index do |stock| %>
						<% price = @price.current(stock[0]) %>
						<tr>
							<th><%= stock[1] %></th>
							<td><%= link_to stock[6], "http://m.yahoo.com/w/yfinance/quote/#{stock[6]}/?chart=1d&.intl=US&.lang=en", :target => '_blank' %></td>
							<td class='aln_r'>$<%= stock[7] %></td>
							<td class='aln_r'><%= stock[8] %></td>
							<td class='aln_r'><%= number_to_percentage (100*(stock[7].to_f - stock[2]) / stock[2]) %></td>
						</tr>
						<% end %>			
				</table>



                </tbody>
              </table>
      
         </div><!-- /content -->

<script>

</script>

app/views/home/news.html.erb
<h3>Tabbable example</h3>
<p>To make tabs tabbable, create a <code>.tab-pane</code> with unique ID for every tab and wrap them in <code>.tab-content</code>.</p>
<div class="bs-docs-example">
  <div class="tabbable tabs-left" style="margin-bottom: 18px;">
    <ul class="nav nav-tabs">
      <li class="active" style='background-color: #08C;'><a href="#tab1" data-toggle="tab">Section 1</a></li>
      <li><a href="#tab2" data-toggle="tab">Section 2</a></li>
      <li><a href="#tab3" data-toggle="tab">Section 3</a></li>
    </ul>
    <div class="tab-content" style="padding-bottom: 9px; border-bottom: 1px solid #ddd;">
      <div class="tab-pane active" id="tab1">
        <p>I'm in Section 1.</p>
      </div>
      <div class="tab-pane" id="tab2">
        <p>Howdy, I'm in Section 2.</p>
      </div>
      <div class="tab-pane" id="tab3">
        <p>What up girl, this is Section 3.</p>
      </div>
    </div>
  </div> <!-- /tabbable -->
</div>

<!-- Docs nav
================================================== -->
<div class="row">
  <div class="span3 bs-docs-sidebar">
    <ul class="nav nav-list bs-docs-sidenav affix">
      <li><a href="#dropdowns"><i class="icon-chevron-right active"></i> Dropdowns</a></li>
      <li style='background-color: #08C;'><a href="#buttonGroups"><i class="icon-chevron-right"></i> Button groups</a></li>
      <li><a href="#buttonDropdowns"><i class="icon-chevron-right"></i> Button dropdowns</a></li>
      <li><a href="#navs"><i class="icon-chevron-right"></i> Navs</a></li>
      <li><a href="#navbar"><i class="icon-chevron-right"></i> Navbar</a></li>
      <li><a href="#breadcrumbs"><i class="icon-chevron-right"></i> Breadcrumbs</a></li>
      <li><a href="#pagination"><i class="icon-chevron-right"></i> Pagination</a></li>
      <li><a href="#labels-badges"><i class="icon-chevron-right"></i> Labels and badges</a></li>
      <li><a href="#typography"><i class="icon-chevron-right"></i> Typography</a></li>
      <li><a href="#thumbnails"><i class="icon-chevron-right"></i> Thumbnails</a></li>
      <li><a href="#alerts"><i class="icon-chevron-right"></i> Alerts</a></li>
      <li><a href="#progress"><i class="icon-chevron-right"></i> Progress bars</a></li>
      <li><a href="#misc"><i class="icon-chevron-right"></i> Misc</a></li>
    </ul>
  </div>
</div>

app/views/home/pictures.html.erb
<style type="text/css">
  body {
    padding-top: 20px;
    padding-bottom: 40px;
  }

  /* Custom container */
  .container-narrow {
    margin: 0 auto;
    max-width: 700px;
  }
  .container-narrow > hr {
    margin: 30px 0;
  }

  /* Main marketing message and sign up button */
  .jumbotron {
    margin: 60px 0;
    text-align: center;
  }
  .jumbotron h1 {
    font-size: 72px;
    line-height: 1;
  }
  .jumbotron .btn {
    font-size: 21px;
    padding: 14px 24px;
  }

  /* Supporting marketing content */
  .marketing {
    margin: 60px 0;
  }
  .marketing p + h4 {
    margin-top: 28px;
  }
</style>

<br>

<div class="container-narrow">

			<h3>Youtube Channels</h3>
			<a href='http://www.youtube.com/winnetkaporteno'>Winnetka Porteno </a><br>
			<a href='http://www.youtube.com/124osprey'>124 Osprey Point</a><br>			
			<br>
	 <h3>Video Cameras</h3>
			<a href='http://winnetka.dyndns.org:8081'>Winnetka Cameras</a><br>
			<a href='http://ospreypointlane.dtdns.net:8081'>Kiawah Cameras</a><br>
			<br>
			
			<h3>Albums</h3>	
	
			<a href='http://picasaweb.google.com/andydenenberg'>Latest Pics</a><br>
			<a href='http://picasaweb.google.com/winnetkaporteno'>Winnetka Porteno </a><br>
			<a href='http://picasaweb.google.com/brasilexplorador'>Brasil Explorador </a><br>
			<a href='http://picasaweb.google.com/scotlandireland2008'>Scotland and Ireland Golf </a><br>
			<a href='http://picasaweb.google.com/410cowboy'>Jackson Hole </a><br>
			<a href='http://www.flickr.com/photos/flirtybirdy/'>Flirty Birdy </a><br>
			<a href='http://picasaweb.google.com/smoothswing626'>Smooth Swing </a><br>
			<a href='http://picasaweb.google.com/denfamone'>CSU Reunion</a><br>
			<a href='http://picasaweb.google.com/sharkhunterswithballs'>Shark Hunters </a><br>



			<a href='http://www.flickr.com/photos/denenberg/sets/'>Flikr Sets </a><br>		  
			<a href='http://picasaweb.google.com/confederateayatollah'h>Confederate Ayatollah </a><br>
			<a href='http://picasaweb.google.com/fabulousgolf'>Fabulous Golf </a><br>




</div>
 <!-- /container -->

app/views/home/start.html.erb
<style>
.top_header {
font-size:22px;	
}
</style>

<div class='row'>
	<div class='span6'>
		<div class='introbox'>

			<br>
			<div class='top_header'>&nbsp;<b>My Portfolios</b>&nbsp;&nbsp;
			<%= link_to 'New Portfolio', '#myModal', :class => 'btn btn-mini btn-info', 'data-toggle' => "modal" %></div><br>
			

			<table class='table table-condensed table-bordered table-striped'>
					<tr>
						<th>Portfolio Name</th>
						<th class='aln_c'>Portfolio Value</th>
						<th>Gain/Loss</th>
					</tr>						
			<% Portfolio.where(:user_id => current_user).each do |portfolio| %>
				<tr>
					<td><%= link_to portfolio.name, stocks_path(:portfolio => portfolio.name), :class => 'btn btn-mini btn-success' %></td>
					<td class='aln_r'><%= number_to_currency(portfolio.current_value) %></td>
					<td class='aln_r'><%= number_to_currency(portfolio.unrealized_gain_loss[0] ) %></td>						
			  </tr>
				<% end %>
				
			</table>

			<%= render '/stocks/partials/new_portfolio' %>

		</div>		    
	</div>
	
	<div class='span6'>
		<div class='introbox'>

			<br>
		<% if [1,2,3,4,5,6].include?(current_user.id) %>
			<div class='top_header'>&nbsp;<b>Family Favorite Results</b>&nbsp;&nbsp;
			<%= link_to 'Details', family_fun_positions_stocks_path, :class => 'btn btn-mini' %></div><br>
			<table class='table table-condensed table-bordered table-striped'>
					<tr>
						<th>Family Member</th>
						<th class='aln_r'>Portfolio Value</th>
						<th class='aln_r'>% Invested</th>
						<th class='aln_r'>Gain/Loss</th>						
					</tr>						
			<% Portfolio.family_rank.each do |user| %>
				<tr>
					<td>
						<% if current_user.name == User.find(user[0]).name %>
						<%= link_to User.find(user[0]).name, stocks_path, :class => 'btn btn-mini btn-success' %>
						<% else %>
						<%= User.find(user[0]).name %>
						<% end %>
					</td>
					<td class='aln_r'><%= number_to_currency(user[1]) %></td>
					<td class='aln_r'><%= number_to_percentage( 100 * (user[1] - user[2]) / user[1] ) %></td>
					<td class='aln_r'><%= number_to_percentage( 100 * (user[1] - 100000)/100000 ) %></td>
			  </tr>
				<% end %>
			</table>
		<% else %>
			<div class='top_header'>&nbsp;<b>Section reserved for Family Members</b>&nbsp;&nbsp;
		<% end %>
		</div>
	</div>

		
			
		</div>		    
	</div>
</div>
<br>
	<div class="row">		
        <div class="span12 schoolbox">	
			<div class='well' style='background-color:white;'>	
				<b style='font-size:20px;'><%= link_to 'Discussion', posts_path %></b>
				<%= link_to 'Add&raquo;'.html_safe, new_post_path(:type_is => 'Discussion') , :class => "btn btn-mini" %><br><br>
				
						<% @disc.each do |post| %>
				    	<b><em style='font-size:16px;'><%= link_to post.title, post_path(post, :type_is => 'Discussion') %></em></b>
				    	<p><%= post.body.html_safe %>
						   <code><%= link_to 'Read Item', post_path(post, :type_is => 'Discussion') %></code> |
			 					 <%= post.created_at.strftime('%b-%d-%Y') %></p>

				<hr>
						<% end %>
							<%= will_paginate @disc, :class => 'pagination pagination-right pagination-small' %>

						
			</div><!--/well-->	
        </div><!--/span-->
     </div><!--/row-->


<script src="http://charts.wikinvest.com/wikinvest/wikichart/javascript/scripts.php" type="text/javascript"></script><div id="wikichartContainer_A04C5EAB-81EB-1ADE-B2D0-7DD4DBC7409A"><div style="width: 390px; text-align: center; vertical-align: center; margin-top: 22px;"><a href="http://get.adobe.com/flashplayer/"><img src="http://cdn.wikinvest.com/wikinvest/images/adobe_flash_logo.gif" alt="Flash" style="border-width: 0px;"/><br/>Flash Player 9 or higher is required to view the chart<br/><strong>Click here to download Flash Player now</strong></a></div></div><script type="text/javascript">if (typeof(embedWikichart) != "undefined") {embedWikichart("http://charts.wikinvest.com/WikiChartMini.swf","wikichartContainer_A04C5EAB-81EB-1ADE-B2D0-7DD4DBC7409A","390","245",{"showAnnotations":"true","liveQuote":"true","ticker":"QQQ","endDate":"18-03-2013","embedCodeDate":"2013-3-18","startDate":"18-09-2012"},{});}</script><div style="font-size:9px;text-align:right;width:390px;font-family:Verdana"><a href="http://www.wikinvest.com/chart/QQQ" style="text-decoration:underline; color:#0000ee;">View the full QQQ chart</a> at <a href="http://www.wikinvest.com/">Wikinvest</a></div>

app/views/home/start.mobile.erb
<style type="text/css">
	.myChart {
		width: 300px;
		height: 200px;
	}
</style>

<script>
	$(document).ready(function(){
		rank = [ ] ;
		<% Portfolio.family_rank.each do |user| %>
		name = <%= "'#{User.find(user[0]).name}'".html_safe %> ;
		value = <%= "#{user[1]}" %> ;
		r1 = [name, value]  ;
		rank.push(r1) ;
		<% end %>
		
	ChartFamilyRank(rank);
});

</script>

<div data-theme="b" data-role="header">
	<span class="ui-title">
    </span>
	<%= link_to_function current_user.name, 'GoAdmin();', 'data-icon' => "home", 'data-theme' => "a" %>

    <%= link_to 'Logout', destroy_user_session_path(:user), :method=>'delete', 'data-role' => "button", 'data-inline' => "true", 'data-direction' => "reverse", 'data-theme' => "a", 'data-icon' => "star", 'data-iconpos' => "left", :class => "ui-btn-right" %>
    </a>
</div>

   <div data-role="content">
	
	
		<div id="barChart" class="myChart"></div>
	
	
		<% Time.zone = 'America/New_York' %>
      <p>As of: <%= Time.zone.now.strftime("%m/%d/%Y %I:%M%p") %> EST</p>
		

    
       <table data-role="table" id="table-custom-2" data-mode="columntoggle" class="ui-body-d ui-shadow table-stripe ui-responsive" data-column-btn-theme="b" data-column-btn-text="Columns to display..." data-column-popup-theme="a" style="margin: auto;">
        
					<tr class="ui-bar-d">
						<th>Family Member</th>
						<th class='aln_c'>Portfolio Value</th>
						<th class='aln_c'>Performance</th>
					</tr>
					
			<% Portfolio.family_rank.each_with_index do |user, i| %>
				<%= i.odd? ? "<tr style='background: #eee;' >".html_safe : "<tr>".html_safe %>
					<td><%= User.find(user[0]).name %></td>
					<td style='text-align:right !important;'><%= number_to_currency(user[1]) %></td>
					<td style='text-align:right !important;'><%= number_to_percentage( 100 * (user[1] - 100000)/100000 ) %></td>
			  </tr>
				<% end %>

				</table>
<p>Started on 01/03/2013 with $100,000</p>
<%= link_to 'My Portfolios', stocks_path, 'data-role' => "button", 'data-icon' => "star", 'data-iconpos' => "left", 'data-mini' => "true", 'data-inline' => 'true', 'data-theme' => "b"  %>
<%= link_to 'Family Positions', family_fun_positions_stocks_path, 'data-role' => "button", 'data-icon' => "star", 'data-iconpos' => "left", 'data-mini' => "true", 'data-inline' => 'true', 'data-theme' => "b" %>


</div><!-- /content -->

<div data-role="footer">
      <h1>Denenberg @2012 | <%= link_to "Full Site", start_path(:mobile => 0), :target => '_blank' %></h1>
</div><!-- /header -->

app/views/home/test_graph.mobile.erb
<!DOCTYPE html>

<html>
<head>
	<title>JQM Charts</title>
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta name="apple-mobile-web-app-capable" content="yes"/>

	<script src="http://code.jquery.com/jquery-1.8.2.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js"></script>

	<%= javascript_include_tag "jquery.jqplot.min" %>
	<%= javascript_include_tag "jqplot/jqplot.pieRenderer.min.js" %>
	<%= javascript_include_tag "jqplot/jqplot.barRenderer.min.js" %>
	<%= javascript_include_tag "jqplot/jqplot.categoryAxisRenderer.min.js" %>
	<%= javascript_include_tag "rockit/underscore.min.js" %>
	<%= javascript_include_tag "rockit/hideAddressBar.js" %>
	<%= javascript_include_tag "rockit/app.js" %>
	
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css" />
	<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/jquery.mobile/1.2.0/jquery.mobile-1.2.0.min.css" />
    <%= stylesheet_link_tag "jqplot/jquery.jqplot.min", :media => "all" %>

	
	<style type="text/css">
		.myChart {
			width: 300px;
			height: 200px;
		}
	</style>
</head>
<body>

<script>
	$(document).ready(function(){
	plot_it();
});

</script>

	<div data-theme="b" data-role="header">
		<span class="ui-title">
	    </span>
		<%= link_to_function 'Signed-in as ' + current_user.name, 'GoAdmin();', 'data-icon' => "home" %>

	    <%= link_to 'Logout', destroy_user_session_path(:user), :method=>'delete', 'data-role' => "button", 'data-inline' => "true", 'data-direction' => "reverse", 'data-theme' => "a", 'data-icon' => "star", 'data-iconpos' => "left", :class => "ui-btn-right" %>
	    </a>
	</div>


<div data-role="content">
	
			<div id="barChart" class="myChart"></div>
				
<br>
	       <table data-role="table" id="table-custom-2" data-mode="columntoggle" class="ui-body-d ui-shadow table-stripe ui-responsive" data-column-btn-theme="b" data-column-btn-text="Columns to display..." data-column-popup-theme="a" style="margin: auto;">

					<tr class="ui-bar-d">
						<th>Family Member</th>
						<th class='aln_c'>Portfolio Value</th>
						<th>Gain/Loss</th>

					</tr>						
			<% Portfolio.family_rank.each_with_index do |user,i| %>
				<%= i.odd? ? "<tr style='background: #eee;' >".html_safe : "<tr>".html_safe %>
					<td>
						<% if current_user.name == User.find(user[0]).name %>
						<%= link_to User.find(user[0]).name, stocks_path, :class => 'btn btn-mini btn-success' %>
						<% else %>
						<%= User.find(user[0]).name %>
						<% end %>
					</td>
					<td style='text-align:right !important;'><%= number_to_currency(user[1]) %></td>
					<td style='text-align:right !important;'><%= number_to_percentage( 100 * (user[1] - 100000)/100000 ) %></td>
			  </tr>
				<% end %>
			</table>

			<%= link_to 'Positions', family_fun_positions_stocks_path, 'data-role' => "button", 'data-icon' => "star", 'data-iconpos' => "left", 'data-mini' => "true", 'data-inline' => 'true', 'data-theme' => "b" %>

	<%= link_to 'Back', start_path, 'data-role' => "button", 'data-icon' => "star", 'data-iconpos' => "left", 'data-mini' => "true", 'data-inline' => 'true', 'data-theme' => "b" %>

	<br>
	<br>
	</div><!-- /content -->

	<div data-role="footer">
	      <h1>Denenberg @2012 | <%= link_to "Full Site", start_path(:mobile => 0), :target => '_blank' %></h1>
	</div><!-- /header -->

	
</body>
</html>

app/views/home/welcome.html.erb
<style>
  body {
    padding-top: 20px;
    padding-bottom: 40px;
  }

  /* Custom container */
  .container-narrow {
    margin: 0 auto;
    max-width: 700px;
  }
  .container-narrow > hr {
    margin: 30px 0;
  }

  /* Main marketing message and sign up button */
  .jumbotron {
    margin: 60px 0;
    text-align: center;
  }
  .jumbotron h1 {
    font-size: 32px;
    line-height: 1;
  }
  .jumbotron .btn {
    font-size: 21px;
    padding: 14px 24px;
  }

</style>

<br>

<div class="container-narrow">


  <div class="jumbotron">
    <h1>Welcome to our Collaboration!</h1><br>
    <p class="lead">Working together to make better investments<br>
					<br>Leveraging each other's insights and experience<br><br>
	</p>
	<%= link_to 'Enter Site and Learn more', start_path, :class => 'btn btn-large btn-success' %>
  </div>

  <hr>
</div>

<br>

app/views/home/welcome.mobile.erb
<style>
.center-wrapper{
text-align: center;
}
.center-wrapper * {
margin: 0 auto;
}
</style>

<!-- Home -->
<div data-role="page" id="page1">
    <div data-theme="a" data-role="header">
        <h3>
            DENvestR
        </h3>
    </div>
    <div data-role="content">
	
		<div class='center-wrapper'>
<br>	
        <h1>Welcome to our Collaboration!</h1>
<br>
        <h3>Working together to make better investments</h3>
<br>
		<h3>Leveraging each other's insights and experience</h3>
<br>
<br>
		<%= link_to 'Start', stocks_path, 'data-role' => "button", 'data-theme' => "e" , :class => 'center-wrapper' %>

		</div>


    <div data-theme="a" data-role="footer" data-position="fixed">
        <h3>
            Denenberg @2013
        </h3>
    </div>
</div>