config/routes.rb
Stc::Application.routes.draw do


  post 'portfolios/create' => 'portfolios#create'

  resources :stocks do
    collection do
      get 'manage_list'
      get 'lookup'
      get 'new_portfolio'
      post 'sell_shares'
      get 'family_fun_positions'
      get 'new_price_time'
    end
  end

  resources :attachments 

  resources :comments do
    member do
      get 'modify'
    end
  end

  resources :posts do
    collection do
      get 'add_comment'
      get 'add_attachment'
    end
  end
    
#  authenticated :user do
#    root :to => 'home#index'
#    root :to => 'home#welcome'
#  end

  root :to => 'home#start'
  
  devise_for :users
  resources :users
  
  get 'home/welcome' => 'home#welcome', :as => :welcome
  get 'home/index' => 'home#index', :as => :index
  get 'home/news' => 'home#news', :as => :news
  get 'home/pictures' => 'home#pictures', :as => :pictures
  get 'home/media' => 'home#media', :as => :media
  
  get 'home/start' => 'home#start', :as => :start
  get 'home/test_graph' => 'home#test_graph', :as => :test_graph
  
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :attachments, :dependent => :destroy
  attr_accessible :body, :title, :user_id, :type_is, :attachments_attributes, :comments_attributes
  has_many :comments, :dependent => :destroy
  has_one :user
  accepts_nested_attributes_for :attachments, :allow_destroy => true
  accepts_nested_attributes_for :comments, :allow_destroy => true
  
  def file_count(kind)
        
    count = 0
    stash = [ ]
    case kind
    when 'image'
      self.attachments.each do |fn|
        if !fn.image_content_type.nil? and fn.image_content_type.include?('image')
          count =+ 1
          stash.push fn
        end
      end        
    when 'file'
      self.attachments.each do |fn|
        if !fn.image_content_type.nil? and !fn.image_content_type.include?('image')
          count =+ 1
          stash.push fn
        end
      end      
    when 'url'
      self.attachments.each do |attach|
        if attach.image_file_name.nil?
          count =+ 1
          stash.push attach
        end
      end      
    end
    
    return count, stash      	    
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
 
  def add_comment
    @post = Post.find(params[:post])
    @post.comments.new
    render :partial => 'add_comment', :layout => false    
  end

  def add_attachment
    @post = Post.find(params[:post])
    @post.attachments.new
    render :partial => 'add_attachments', :layout => false    
  end
    
  def index
    if params[:type_is] == 'Discussions & News' or params[:type_is] == nil
      type_is = '' 
    else 
      type_is = 'type_is = "' + params[:type_is] + '"' 
    end

    @type_is = 'Discussion' # params[:type_is]
    type_is = 'type_is = "Discussion"'

    @posts = Post.where(type_is).paginate(:page => params[:page], :per_page => 5).order('created_at desc')
    
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @type_is = params[:type_is]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @type_is = params[:type_is]
    @post = Post.new
    @post.attachments.build
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    @type_is = params[:type_is]
    
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  
  def type_color(type_is)
    color = 'label'
    if type_is == 'News'
      color = 'label label-info'
    elsif type_is == 'Discussion'
      color = 'label'
    end  
    return color
  end  
  
end

app/views/posts/_add_attachments.html.erb
<%= simple_form_for(@post, :html => { :class => 'form-vertical span9' } ) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
		<%= f.fields_for :attachments do |attach| %>
		
		  	<% if attach.object.new_record? %>
				<h4>Attachments:</h4>
				<div class='row'>
					<div class='span4'>
							<label for="stackedSelect">URL</label>
							<%= attach.text_field :url , :class => "input span3"%>
							<label for="stackedSelect">Description</label>
							<%= attach.text_field :description , :class => "input span8" %>
					</div>
					<div class='span4'>
							<label for="stackedSelect">File</label>
							<%= attach.file_field :image %>
					</div>
				</div>
			<% end %>
		<% end %>
	
  </div>

  <div class="form-actions">
    <%= f.button :submit , 'Save' %> | 
	<%= link_to 'Cancel', @post %>
  </div>
<% end %>

app/views/posts/_add_comment.html.erb
<%= simple_form_for(@post, :html => { :class => 'form-vertical span9' } ) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
	<h4>Comments:</h4>
		<%= f.fields_for :comments do |comment| %>
		
		<% if comment.object.new_record? %>
			  <div class="form-inputs">
				<label for="stackedSelect">New Comment</label>
			    <%= comment.text_area :note , :class => "input textarea span8", :rows => 5  %>
				<%= comment.hidden_field :user_id , :value => current_user.id %>
			  </div>
		<% end %>

	<% end %>
	
  </div>

  <div class="form-actions">
    <%= f.button :submit , 'Save' %> | 
	<%= link_to 'Cancel', post_path(@post, :type_is => 'Discussion') %>
  </div>
<% end %>

app/views/posts/_comments.html.erb
<div class='row'>
	<div class='span9 offset1'>
		<%= link_to_function 'Add Comment', "AddComment(" + @post.id.to_s + "); return false", :class => 'btn btn-primary btn-mini', :id => 'add_comment_button' %>
		<br><br>

	<% @post.comments.each do |c| %>

		<blockquote>
			<%= c.note.html_safe %>
			<br><br>
			<div class='pull-right'>
			<b><%= User.find(c.user_id).name %></b> on <%= c.created_at.strftime('%b %d, %Y') %>
			<% if current_user.id == c.user_id %> |
			    <%= link_to 'Edit', modify_comment_path(c), :class => 'btn btn-mini' %> |
			    <%= link_to 'Remove', c, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-warning' %> 
			<% end %>
		</blockquote><br>
		<hr>
	<% end %>
	
	</div>
</div>

app/views/posts/_form.html.erb
<div class="row">
  <div class="span10 offset1">

<%= simple_form_for(@post, :html => { :class => 'form-vertical span9' } ) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
	<div class='form-box'>
		<div class='row'>
			<div class='span4'>
				<label for="stackedSelect">Title</label>
    			<%= f.text_field :title  , :class => "span4" %>
			</div>
				<%= f.hidden_field :type_is , :value => 'Discussion' %>
		</div>		
		<label for="stackedSelect">Message</label>
	    <%= f.text_area :body , :class => "input textarea span8", :rows => 10  %>
		<%= f.hidden_field :user_id , :value => current_user.id %>
	</div>

		<% i = 0 %>
		<%= f.fields_for :attachments do |attach| %>
		<div class='form-box'>
		<div class='row'>
			<div class='span4'>
				<% if !attach.object.new_record? %>
				<label class="checkbox inline">
			<!--- attach.check_box :_destroy, {:checked => attach.object.persisted?}, '0', '1' %>Save Attachment? ---->
					<%= attach.check_box :_destroy %><b>Delete Attachment <%= i ; i += 1 %></b>					
				</label>
				<% else %>
				<label for="stackedSelect"><b>Attachment</b></label>
				<% end %>				
			</div>
		</div>
		<br>
		<div class='row'>
			<div class='span4'>
					<label for="stackedSelect">URL</label>
					<%= attach.text_field :url , :class => "input span3"%>
					<label for="stackedSelect">Description</label>
					<%= attach.text_field :description , :class => "input span8" %>
			</div>
			<div class='span4'>
					<label for="stackedSelect">Current File: <b><%= attach.object.image_file_name %></b></label><br>
					<%= attach.file_field :image %>
			</div>
		</div>
		</div>
	<% end %>
	
  </div>

  <div class="form-actions">
    <%= f.button :submit , 'Save' %> | 
	<%= link_to 'Cancel', @post %>
  </div>
<% end %>

	</div>
</div>

app/views/posts/_index.html.erb
<% @posts.each do |post| %>
	<% post.body.length > 300 ? body = post.body[0..300].html_safe : body = post.body.html_safe %>
		<div class='row'>
			<div class='span11'>
				<div class='row introbox  offset1' style='min-height: 110px;'>
					<div class='span4'>
							<div class='lead' style='border-bottom:thin dotted #000000;
							}'><%= link_to post.title, post_path(post, :type_is => @type_is) %></div>
							<small><%= User.find(post.user_id).name ||= '' %> on <%= post.created_at.strftime('%b-%d-%Y') %> |
							Comments: <%= post.comments.count %> | <%= post.id %>
							<span class="<%= type_color(post.type_is) %>">
							<%= link_to 'Read ' + post.type_is, post_path(post, :type_is => @type_is), :style => 'color:white;' %></span></small><br><br>
							
					</div>
					<div class='span5'>
						<% if post.attachments.count > 0 %>
							<b>Attachments</b>
						<ol>
						<% post.attachments.each_with_index do |attach| %>
							<li>
							<% if !attach.url.blank? %>
								<code>Link: <%= link_to attach.url, "http://" + attach.url, :target => '_blank' %></code>
							<% end %>
							<% if !attach.image.url.include?('missing.png') %>
							<code>File: <%= link_to attach.image_file_name, attach.image.url, :target => '_blank' %></code>
							<% end %>
							<%= attach.description.html_safe %>
							</li>
							<% end %> 
						<% end %>
						
						<%= body %><br>
						
					</div>
					<br>
				</div>
			</div>
		</div>
		<br><br>		
<% end %>
<%= will_paginate @posts, :class => 'pagination pagination-centered pagination-small', :style => 'vertical-align:middle;'%>

app/views/posts/_show.html.erb
<div class="row">
  <div class="span12">
	  <div class='blank_box'>
		
		<div class='lead' style='border-bottom:thin dotted #000000;'><%= link_to @post.title, @post %></div>

<% if @post.attachments.count > 0 %>
	<b>Attachments</b>
<ol>
<% @post.attachments.each_with_index do |attach| %>
	<li>
	<% if !attach.url.blank? %>
		<code>Link: <%= link_to attach.url, "http://" + attach.url, :target => '_blank' %></code>
	<% end %>
	<% if !attach.image.url.include?('missing.png') %>
	<code>File: <%= link_to attach.image_file_name, attach.image.url, :target => '_blank' %></code>
	<% end %>
	<%= attach.description.html_safe %>
	</li>
	<% end %> 
<% end %>
<br>
<p style='font-size:16px;line-height:120%;'><%= @post.body.html_safe %></p>
	
	
	
	</div>	
	

	<div class='row pull-right'>
		<% if current_user.id == @post.user_id %>
			<%= link_to_function 'Add Attachment', "AddAttachment(" + @post.id.to_s + "); return false", :class => 'btn btn-mini btn-primary' %>			<%= link_to 'Edit', edit_post_path(@post, :type_is => @type_is), :class => 'btn btn-mini' %>
			<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-warning' %>
		<% end %>
		
	Created by: <b><%= User.find(@post.user_id).name %></b> on <%= @post.created_at.strftime('%b %d, %Y') %>
	</div><br>
	    
	<div id='comment'></div>

	<%= render 'comments'%>
	
  </div><!--/span-->


</div><!--/row-->

<br>

app/views/posts/edit.html.erb
<div class="row">
  <div class="span3 offset1">
	<ul class="breadcrumb">
	  <li><%= link_to 'Home', start_path %> <span class="divider">/</span></li>
	  <li><%= link_to @post.type_is, posts_path(:type_is => @post.type_is ) %> <span class="divider">/</span></li>
	  <li>Item: <%= @post.id %></li>	
	</ul>
  </div>
</div>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="row">
  <div class="span3 offset1">
	<ul class="breadcrumb">
	  		<li><%= link_to 'Home', start_path %> <span class="divider">/</span></li>
		<% if @type_is != nil %>
	  		<li class="active"><%= @type_is %></li>
		<% else %>
			<li><%= link_to 'Discussion', posts_path(:type_is => 'Discussion') %> <span class="divider">/</span></li>
			<li><%= link_to 'News', posts_path(:type_is => 'News') %> </li>
		<% end %>
	</ul>
  </div>
  <div class='span8'>
 
		<% if @type_is == 'Discussion' %>
		  <%= link_to 'Add Discussion Item', new_post_path(:type_is => 'Discussion'), :class => 'btn btn-mini' %>
		<% elsif @type_is == 'News' %>
		  <%= link_to 'Add News Item', new_post_path(:type_is => 'News'), :class => 'btn btn-info btn-mini' %>
		<% else %>
		  <%= link_to 'Add Discussion Item', new_post_path(:type_is => 'Discussion'), :class => 'btn btn-mini' %>
		  <%= link_to 'Add News Item', new_post_path(:type_is => 'News'), :class => 'btn btn-info btn-mini' %>		
		<% end %>	
  </div>
</div>
<br>

<div id='table'>
	<%= render 'index' %>
</div>


<br />

		  <%= select_tag "type_is", options_for_select(['Discussions & News', 'Discussion', 'News'], :selected => @type_is), :class => 'span2' %>

app/views/posts/index.js.erb
$("#table").html("<%= escape_javascript(render("index")) %>");

app/views/posts/new.html.erb
<h3>New Item</h3>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="row">
  <div class="span3">
	      <%= link_to 'Home', start_path, :class => 'btn btn-mini' %> <span class="divider">/</span></li>
		  <%= link_to 'New Discussion Item', new_post_path(:item_type => 'Discussion'), :class => 'btn btn-mini' %>
  </div>
</div>

<%= render 'show' %>