config/routes.rb
Stc::Application.routes.draw do


  post 'portfolios/create' => 'portfolios#create'

  resources :stocks do
    collection do
      get 'manage_list'
      get 'lookup'
      get 'new_portfolio'
      post 'sell_shares'
      get 'family_fun_positions'
      get 'new_price_time'
    end
  end

  resources :attachments 

  resources :comments do
    member do
      get 'modify'
    end
  end

  resources :posts do
    collection do
      get 'add_comment'
      get 'add_attachment'
    end
  end
    
#  authenticated :user do
#    root :to => 'home#index'
#    root :to => 'home#welcome'
#  end

  root :to => 'home#start'
  
  devise_for :users
  resources :users
  
  get 'home/welcome' => 'home#welcome', :as => :welcome
  get 'home/index' => 'home#index', :as => :index
  get 'home/news' => 'home#news', :as => :news
  get 'home/pictures' => 'home#pictures', :as => :pictures
  get 'home/media' => 'home#media', :as => :media
  
  get 'home/start' => 'home#start', :as => :start
  get 'home/test_graph' => 'home#test_graph', :as => :test_graph
  
  
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) and !msg == 'Signed in successfully.' %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<script>
$(document).ready(function(){
	<% if current_user %>
		window.setInterval(function() {
		 	getPriceData();
		}, 10000);	
	<% end %>	
});
</script>

<%= link_to 'DENvestR', start_path, :class => 'brand' %>

<% if user_signed_in? %>

<ul class='nav'>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Family Site <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Family Site', 'http://www.denenberg.net', :target => '_blank' %></li>
      <li class="divider"></li>
      <li class="nav-header">Pictures</li>
      <li><%= link_to 'Family Pictures', pictures_path %></li>
    </ul>
  </li>
</ul>

<ul class='nav'>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Collaboration<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li class="nav-header">Information</li>
      <li><%= link_to 'Discussion and Messages', posts_path %></li>
    </ul>
  </li>
</ul>

<ul class='nav'>
<li class='active'><%= link_to ' ', '#', :id => 'ticker' %></li>
</ul>
<% end %>


<ul class="nav pull-right">
  <% if user_signed_in? %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
    <ul class="dropdown-menu">
	    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
      	<li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
	    <% if current_user.has_role? :admin %>
	      <li><%= link_to 'Admin', users_path %></li>
	    <% end %>
    </ul>
  </li>
  <% else %>
    <li><%= link_to 'Login', new_user_session_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "nvestr" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "nvestr" %>">
	    <%= stylesheet_link_tag "application", :media => "all" %>
	    <%= javascript_include_tag "application" %>
	    <%= csrf_meta_tags %>
	    <%= yield(:head) %>	
  </head>
  <body class="<%= controller_name %> <%= action_name %>" >
    <header class="navbar navbar-inverse navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer class='center_text'>
				<br><br><br><small>Denenberg @2012 | <%= link_to "Mobile Site", stocks_path(:mobile => 1), :target => '_blank' %></small><br><br>
          </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "nvestr" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "DENvestR" %>">

    <%= csrf_meta_tags %>


		<link rel="stylesheet" href="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css" />
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/jquery.mobile/1.2.0/jquery.mobile-1.2.0.min.css" />
		<script src="http://code.jquery.com/jquery-1.8.2.min.js"></script>
		<script src="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js"></script>
				
		<%= javascript_include_tag "application" %>
		<%= stylesheet_link_tag "jqplot/jquery.jqplot.min" %>
		
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

 </head>
  <body>
	
      <div class="container">
              <%= yield %>
      </div>
  </body>		

</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Stc" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Stc" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-inverse navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
              <%= yield %>
          <footer class='center_text'>
				<br><br><br><small>LSSC @2012</small><br><br>
          </footer>
    </div> <!--! end of #main -->
  </body>
</html>